spring:
  # Database
  r2dbc:
    url: r2dbc:postgresql://172.17.0.2:5432/postgres?schema=techwriting
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    #hibernate:
      #ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
logging:
  level:
    org.springframework.data.r2dbc: DEBUG